In [1]:
import numpy as np
import scipy
import math
import sympy

In [2]:
import numpy as np

def householder_transformation(A):
    m, n = A.shape
    R = np.copy(A)
    Q = np.eye(m)

    for k in range(min(m, n)-1):
        x = R[k:, k]
        e = np.zeros_like(x)
        e[0] = 1
        v = np.sign(x[0]) * np.linalg.norm(x) * e + x
        v = v / np.linalg.norm(v)
        R[k:, k:] -= 2.0 * np.outer(v, (v @ R[k:, k:]))
        # Accumulate the transformations to form the Q matrix
        Qk = np.eye(m)
        Qk[k:, k:] -= 2.0 * np.outer(v, v)
        Q = Q @ Qk.T
        print(k,Q)

    return Q,R

A = np.array([[1.0,1.0,1.0],[1.0,2.0,4.0],[1.0,3.0,9.0],[1.0,4.0,16.0]])
Q, R = householder_transformation(A)

print("Original matrix A:")
print(A)
print("\nQ matrix:")
print(Q)
print("\nR matrix:")
print(R)
print("\nProduct of Q and R:")
print(np.dot(Q, R))


0 [[-0.5        -0.5        -0.5        -0.5       ]
 [-0.5         0.83333333 -0.16666667 -0.16666667]
 [-0.5        -0.16666667  0.83333333 -0.16666667]
 [-0.5        -0.16666667 -0.16666667  0.83333333]]
1 [[-0.5        -0.67082039 -0.4236068  -0.3472136 ]
 [-0.5        -0.2236068   0.30601133  0.77868933]
 [-0.5         0.2236068   0.65879773 -0.51573787]
 [-0.5         0.67082039 -0.54120227  0.08426213]]
Original matrix A:
[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]

Q matrix:
[[-0.5        -0.67082039 -0.4236068  -0.3472136 ]
 [-0.5        -0.2236068   0.30601133  0.77868933]
 [-0.5         0.2236068   0.65879773 -0.51573787]
 [-0.5         0.67082039 -0.54120227  0.08426213]]

R matrix:
[[-2.00000000e+00 -5.00000000e+00 -1.50000000e+01]
 [-2.22044605e-16  2.23606798e+00  1.11803399e+01]
 [-2.22044605e-16 -2.22044605e-16 -1.92961813e+00]
 [-2.22044605e-16 -4.44089210e-16 -5.25902921e-01]]

Product of Q and R:
[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4

In [3]:
#np.linalg.eig
#scipy.linalg.svdvals


In [20]:
def calceigen(A):
    return sympy.simplify(scipy.linalg.eig(A,left=True))

A=[[-149,-50,-154],[537,180,546],[-27,-9,-25]]
calceigen(A)

([1.00000000000545, 1.99999999999397, 3.00000000000058], [[0.681029754033944, 0.676269195730612, 0.688247201611739], [0.225263687872776, 0.225423065243528, 0.229415733870575], [0.696745825280943, 0.701316202979856, 0.688247201611628]], [[0.316227766016994, -0.404061017819311, -0.139139989880397], [-0.948683298050462, 0.909137290097895, 0.973979929161851], [-1.80231095861106e-13, 0.101015254453369, -0.178894272703066]])

In [5]:
def svdvals(A):
    return sympy.simplify(scipy.linalg.svdvals(A))
A=[[1,2,3],[4,5,6],[7,8,9]]
svdvals(A)

[16.8481033526142, 1.06836951455471, 3.33475286503143e-16]

In [21]:
#To calculate norm of a matrix
def norm(A,k):
    return sympy.simplify(scipy.linalg.norm(A,ord=k))
A=[[0.681029754033944,0.676269195730612,0.688247201611739],[0.225263687872776,0.225423065243528,0.229415733870575],[0.6967,0.70131,0.6882]]
norm(A,2)

1.73196137549816

In [7]:
#To calculate inverse of a matrix()
def inverse(A):
    return sympy.simplify(scipy.linalg.inv(A))
A=[[3,-1,-1],[-1,3,-1],[-1,-1,3]]
inverse(A)

[[0.5, 0.25, 0.25], [0.25, 0.5, 0.25], [0.25, 0.25, 0.5]]

In [8]:
#Calculate condition number
def condition_number(A):
    return sympy.simplify(np.linalg.cond(A))

A=[[1,2,3],[4,5,6],[7,8,9]]
condition_number(A)

5.05227944453851e+16

In [9]:
#To do lu transformation:
def lu(A):
    #Specify if you want to permute in permute_l
    return sympy.simplify(scipy.linalg.lu(A))
    #Returns P,L,U
A=[[3,5],[6,7]]
lu(A)

([[0.0, 1.0], [1.0, 0.0]], [[1.0, 0.0], [0.5, 1.0]], [[6.0, 7.0], [0.0, 1.5]])

In [10]:
#Calculate cholesky decomposition
def cholesky(A):
    return sympy.simplify(scipy.linalg.cholesky(A))
A=[[3,-1,-1],[-1,3,-1],[-1,-1,3]]
cholesky(A)

[[1.73205080756888, -0.577350269189626, -0.577350269189626], [0.0, 1.63299316185545, -0.816496580927726], [0.0, 0.0, 1.4142135623731]]

In [11]:
#Return QR factorization
def QR(A):
    return sympy.simplify(scipy.linalg.qr(A))
A=[[3,-1,-1],[-1,3,-1],[-1,-1,3]]
QR(A)

([[-0.904534033733291, -0.123091490979333, 0.408248290463863], [0.301511344577764, -0.861640436855329, 0.408248290463863], [0.301511344577764, 0.492365963917331, 0.816496580927726]], [[-3.3166247903554, 1.50755672288882, 1.50755672288882], [0.0, -2.95419578350399, 2.46182981958666], [0.0, 0.0, 1.63299316185545]])

In [12]:
def givens_rotation(A):
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()

    for j in range(n):
        for i in range(m-1, j, -1):
            if R[i, j] != 0:
                # Compute the Givens rotation matrix
                c = R[i-1, j] / np.sqrt(R[i-1, j]**2 + R[i, j]**2)
                s = -R[i, j] / np.sqrt(R[i-1, j]**2 + R[i, j]**2)
                G = np.eye(m)
                G[i-1:i+1, i-1:i+1] = np.array([[c, -s], [s, c]])

                # Update the matrices Q and R
                R = np.dot(G, R)
                Q = np.dot(Q, G.T)

    return Q, R

# Example usage:
# Replace 'your_matrix' with your actual matrix
A = np.array([[1.0,0,0],[0,1.0,0],[0,0,1.0],[-1.0,1,0],[-1.0,-0,1],[0,1.0,1.0]])
Q, R = givens_rotation(A)

print("Original Matrix:")
print(A)

print("\nQ Matrix:")
print(Q)

print("\nR Matrix:")
print(R)

# Verify the decomposition: Q * R should be approximately equal to the original matrix
print("\nQ * R:")
print(np.dot(Q, R))


Original Matrix:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [-1.  1.  0.]
 [-1.  0.  1.]
 [ 0.  1.  1.]]

Q Matrix:
[[ 0.57735027  0.20412415  0.15811388 -0.77459667  0.          0.        ]
 [ 0.          0.61237244 -0.15811388  0.12909944 -0.76376262  0.        ]
 [ 0.          0.          0.63245553  0.12909944 -0.10910895 -0.75592895]
 [-0.57735027  0.40824829 -0.31622777 -0.38729833  0.32732684 -0.37796447]
 [-0.57735027 -0.20412415  0.47434165 -0.38729833 -0.32732684  0.37796447]
 [ 0.          0.61237244  0.47434165  0.25819889  0.43643578  0.37796447]]

R Matrix:
[[ 1.73205081e+00 -5.77350269e-01 -5.77350269e-01]
 [-8.89809642e-18  1.63299316e+00  4.08248290e-01]
 [-6.89243585e-18 -7.06032206e-17  1.58113883e+00]
 [ 3.37659018e-17 -1.44118221e-17 -1.46970215e-17]
 [ 0.00000000e+00  7.72423867e-17 -2.03727640e-18]
 [ 0.00000000e+00 -7.26811578e-17 -3.32886356e-17]]

Q * R:
[[ 1.00000000e+00  9.72785220e-18 -2.33489614e-18]
 [-1.72269555e-34  1.00000000e+00  3.66292440e-17]
 [