In [1]:
import numpy as np
import sys

In [2]:
#Create 1D numpy array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
#Create 2D numpy array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
#Get the number of dimensions for each array
print(a.ndim)
print(b.ndim)

1
2


In [5]:
#The shape of each array
print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [6]:
#Get the data type for each array
print(a.dtype)
print(b.dtype)

int32
float64


In [7]:
#Get the item size for each array
print(a.itemsize)
print(b.itemsize)

4
8


In [8]:
#Get the total size of each array
print(a.nbytes)
print(b.nbytes)

16
48


## Accessing elements

In [9]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [10]:
#Print a specific element
print(c[1,3])

9


In [11]:
#Get a specific row
print(c[0,:])

[1 2 3 4 5]


In [12]:
#Get a specific column
print(c[:,1])

[2 7]


In [13]:
#[start:stop:skip]
print(c[0,0:5:2])

[1 3 5]


## Initializing arrays

In [14]:
#Create a 1D array of zeros
d = np.zeros(5)
print(d)

[0. 0. 0. 0. 0.]


In [15]:
#Create a 2D array of zerps
e = np.zeros((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#Create a 3D arrya of ones of 1d type
f = np.ones((4,2,2), dtype = 'int32')
print(f)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [17]:
#Print a full array of any number
g = np.full((4,2,2),10)
print(g)

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [18]:
#Random matrix
h = np.random.rand(4,2)
print(h)

[[0.40222341 0.06499799]
 [0.44981276 0.26933377]
 [0.39584764 0.18553239]
 [0.2326215  0.48484351]]


In [19]:
#Random integer matrix
i = np.random.randint(5,size=(3,3))
print(i)

[[0 2 0]
 [1 3 0]
 [3 3 3]]


In [20]:
#Identity matrix
j = np.identity(3)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#Repeat an array
k = np.array([[1,2,3]])
r1 = np.repeat(k,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
#Copy numpy array
l = k.copy()
print(l)

[[1 2 3]]


## Linear Algebra


In [23]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [24]:
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [25]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
## Print the max min of each column and each row
print(np.max(stats,axis=1))
print(np.max(stats,axis=0))
print(np.min(stats,axis=1))
print(np.min(stats,axis=0))

[3 6]
[4 5 6]
[1 4]
[1 2 3]


## Reorganising arrays

In [27]:
#Reshaping arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)
transpose = before.transpose()
print(transpose)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


##  Stacking

In [28]:
#Vertical Stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

v3 = np.vstack([v1,v2])
print(v3)


[[1 2 3 4]
 [5 6 7 8]]


In [29]:
#Horizontal Stacking
h1 = np.ones((2,2))
h2 = np.zeros((2,2))
h3 = np.hstack([h1,h2])
print(h3)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
